name: "HASecure"
description: "This add-on should be able to extract information from the devices in the system and look for vulnerabilities."
version: "0.1.0"
slug: "hasecure"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
panel_title: Security
panel_icon: mdi:security-network
ingress: true